### PR TITLE
Create roadmap-item.md

### PR DESCRIPTION
**Pull request by vincent6767**
# Description
The context of the roadmap item can be read here: https://github.com/o3de/sig-release/issues/79.

# Action Needed
Since the RFC leverage three labels, kind/roadmap, needs-triage, and triage/accepted, please create this label in your SIG repo if it does not exist already once you merge the PR.

### needs-triage
Taken from [O3DE label](https://github.com/o3de/o3de/labels?q=needs-triage)
- label name: needs-triage
- description: Indicates an issue or PR lacks a triage/foo label and requires one

### triage/accepted
Taken from [O3DE Label](https://github.com/o3de/o3de/labels?q=triage%2Faccepted)
- label name: triage/accepted
- description: Indicates an issue or PR is ready to be actively worked on.

### kind/roadmap
Taken from [O3DE Label](https://github.com/o3de/o3de/labels?q=kind%2Froadmap)
- label name: **kind/roadmap**
- description: **Categorizes an issue that goes in the O3DE Public Roadmap**

Signed-off-by: Vincent <vincentbiasa6767@gmail.com>

### CODE REVIEW

**Comment by vincent6767** [comment]
@galibzon @thefranke Please help review!

**Comment by vincent6767** [comment]
@galibzon @thefranke Friendly reminder to review!

**Comment by vincent6767** [comment]
Hi @galibzon @thefranke, a friendly reminder to help review by next week as we want to target to have every SIGs have a roadmap by February 10th, 2023.

**Comment by thefranke** [comment]
Hey @vincent6767 we've added the roadmap here:
https://github.com/orgs/o3de/projects/41/views/1

It's still set to private, we need someone to later turn it into a public project.

**Comment by vincent6767** [comment]
I can access the project through. Anyway, @amzn-changml can you help turn the project into a public project?

**Comment by vincent6767** [comment]
Hi @galibzon @thefranke can you help merge this PR and apply the kind/roadmap label to the roadmap item in here https://github.com/orgs/o3de/projects/41/views/1? 

Hi @amzn-changml in case you miss the notification. Can you help turn the project into a public project?

**Comment by amzn-changml** [comment]
> Hi @amzn-changml in case you miss the notification. Can you help turn the project into a public project?

Sure, it is public now

**Comment by vincent6767** [comment]
Thanks @amzn-changml !

CC: @thefranke

**Comment by vincent6767** [comment]
Hi @thefranke @galibzon Any chance we can get this PR merged by next week?

**Review by galibzon — APPROVED** [review]

**Pull request closed without merging**
